# Generated by Django 5.0.1 on 2024-04-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
