# Generated by Django 5.0.4 on 2024-05-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_alter_vehicle_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicledetail',
            old_name='engineer_size',
            new_name='capacity',
        ),
        migrations.AddField(
            model_name='vehicledetail',
            name='horsepower',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
